### ISSUE TITLE
New README about non-code license

### ISSUE THREAD

**Issue by diovudau** [reales/OB-Xd#82]
Hello,

I saw the new addition to the README (quoted below). Could you please clarify what that means (what is your intention?) for the existing versions and packages, e.g. in Linux distributions.

```
This repository will remain available for historic purposes and the source code remains GPL3, however any artwork, GFX, non-credited FXB banks, MIDI XML templates, PDF manual or any non-source code related assets or blobs always had all rights reserved to discoDSP and are not tied to the GPL license. They apply the following conditions:

You are expressly prohibited from copying, modifying, merging, selling, leasing, redistributing, assigning, or transferring in any matter any portion.

You may not remove, alter, deface, overprint or otherwise obscure licensor patent, trademark, service mark or copyright notices.

You may not publish or distribute in any form of electronic or printed communication the materials without permission.
```

**Comment by reales** [comment]
Our existing source code will remain under GPL3 for now. Distributing any packages or copyrighted materials from discoDSP is not allowed. You should get them directly from https://www.discodsp.com/obxd/ and obey the new trial conditions or purchase the registered license for commercial purposes.

**Comment by diovudau** [comment]
But what happens with the existing packages that already exist? That are based on the old state, with the previous owner,  such as https://archlinux.org/packages/community/x86_64/ob-xd/

**Comment by reales** [comment]
Distribution of packages containing our copyrighted materials, as always, require a license or permission.

**Comment by diovudau** [comment]
Assuming that the current packages in linux distributions did not ask you for permission or a license, and assume that the whole project including non-code files, were always part of "free and open source" software and data, do you require them to remove the current packages if they will never ask for permission/license?

**Comment by falkTX** [comment]
the GPL license mentions that there is no permission required for, among other things, redistrbution.
you cant retroactively change the license of past releases.

if you really mean to state that past releases needed special permissions, the project was never GPL in the first place then.

**Comment by zamaudio** [comment]
@reales Are you saying all clones of your public repo are now illegal?  Can you please provide a timestamp for when this transfer of ownership occurred, I think you owe it to the community to know this vital piece of the puzzle.

**Comment by reales** [comment]
Considering it’s non-profit, there are no consequences for a distribution like that. The GPL applies for the source code. Images, assets are other blobs and assets have always being copyrighted to discoDSP.

**Comment by falkTX** [comment]
except it is all part of a final single binary, covered by GPL, and thus due to its "virality" all parts inside the binary are also to be GPL compatible.

being for profit or not is meaningless here btw, you are trying to retroactively change license of published GPL binaries and projects. I have an old copy that never got your involvement in it, how can you say you own that now?

**Comment by reales** [comment]
Only previous binary compiled files and the source code are covered by the GPL. Blobs and asset files are never legally tied to this license. The decision to include copyrighted materials in a profitable public distribution without the author permission is probably a risk.

**Comment by zamaudio** [comment]
This may be useful to keep here:

![image](https://user-images.githubusercontent.com/3164348/208304473-af62f75d-6774-4b7d-a8a1-a08dd1ccfb1d.png)

**Comment by gitterdude** [comment]
I'm far from a copyright expert but from what I can see in the v2.10 git tree (commit 2afc035ac3e)  I have there is only one license covering the project files and that's the GPL v3 license.txt file at the top.

A quick search shows that there are some files that are copyright Filatov Vadim but they are also explicitly licensed under GPL v2.
There's one file Source/Engine/Tuning.h that's copyright discoDSP but that presumably also falls under the GLP.

There's nothing suggesting that blobs, the manual and asset files are under any license other than the overarching GPL v3.

Below may not be be legal advice from a GPL expert but may be relevant advice 
https://opensource.stackexchange.com/questions/12618/can-i-keep-images-and-other-non-code-assets-copyrighted-in-a-gpl-codebase

**Comment by reales** [comment]
I have pushed a updated readme that should clarify things. Also binary resources who contained images have been removed.

**Comment by falkTX** [comment]
It is still not really good, which images are on the repo that have copyright?
You mention there is no permission to copy, so forking is also not allowed (because it makes a copy). You cannot restrict copying in such manner as it is a breakage of GitHub ToS.

**Comment by reales** [comment]
Right now the copyright is about the images from previous commits located on Documents folder that have been removed and the binary data that is also removed.

I will think about what to do for the just in case scenario. Forking the current commit has no issues at all so I will probably remove the discoDSP copyright notice later too.

No idea which ToS breakage are you talking about by the way. I'd appreciate if you point it up.

**Comment by falkTX** [comment]
> No idea which ToS breakage are you talking about by the way. I'd appreciate if you point it up.

somewhere in the ToS there is a mention that it is not allowed to forbid to copying of source code and project files.

it has come up before where a project tried to dictate that forking or copying would not be allowed, but by hosting on github it invalidates those claims.
sorry I dont recall more details, was one of the stupid silly things that just randomly appeared one day, quickly forgotten the next day.
but was enough to know that one cannot have license terms that forbid redistribution and copying while on github.

**Comment by reales** [comment]
Ok, the project does not contain any files not allowed to be copied now.

**Comment by gitterdude** [comment]
Removing files from the current repo still leaves the question regarding those files in old clones or forks.
From what I can tell there was nothing to suggest they had a different licence than the overarching GPL v3 in license.txt

**Comment by gitterdude** [comment]
I'm far from a GPL expert so I can't comment on whether that's true or not but the link I posted above suggests that trademark and logos aside images and similar things would also fall under GPL.

> Section 7 (especially 7.e) of [GPLv3](https://www.gnu.org/licenses/gpl-3.0.de.html) provides the basis for what you want to do, as it allows the limitation of rights for trademarks and logos. It will be difficult to argue that for all graphics/images in the app, or even for the color scheme, but where a trademark/logo can be reasonably assumed you can restrict the use


Did you retain sole copyright over the themes made by Ilkka Rosma and Rin Elyran? 
It would be nice to have them reinstated at least, if that's not the case.

**Comment by reales** [comment]
Yes.

**Comment by gitterdude** [comment]
What about the "013 - KVR Community Bank - Part 1.fxb" and "014 - KVR Community Bank - Part 2.fxb" and possibly all of the KVR banks?
The name "Community Bank" does suggest that it was created by the KVR community.

**Comment by reales** [comment]
Synth presets and synth patches are not subject to copyright which means you can use them for free or  commercially without running into any legal problems except in some cases where something like PCM audio files, artwork or similar elements are used.
